apiVersion: v1
kind: Service
metadata:
  name: ticket-backend
spec:
  type: NodePort
  selector:
    app: ticket-backend
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 31808
