apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-frontend
spec:
  replicas: 1   # 초기 Pod 개수
  selector:
    matchLabels:
      app: ticket-frontend
  template:
    metadata:
      labels:
        app: ticket-frontend
    spec:
      containers:
        - name: ticket-frontend
          image: victory11942656/ticket-frontend:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always

          # ★ HPA가 CPU를 측정하기 위해 꼭 필요한 부분
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
