apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticket-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ticket.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ticket-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ticket-backend
                port:
                  number: 8080
