# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pvc
#   namespace: default
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mysql
#   namespace: default
# spec:
#   serviceName: mysql
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#         - name: mysql
#           image: mysql:8.0
#           ports:
#             - containerPort: 3306
#           env:
#             - name: MYSQL_ROOT_PASSWORD
#               value: "9193"
#             - name: MYSQL_DATABASE
#               value: "ticket"
#           volumeMounts:
#             - name: mysql-storage
#               mountPath: /var/lib/mysql
#   volumeClaimTemplates:
#     - metadata:
#         name: mysql-storage
#       spec:
#         accessModes: ["ReadWriteOnce"]
#         resources:
#           requests:
#             storage: 5Gi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   namespace: default
# spec:
#   ports:
#     - port: 3306
#       targetPort: 3306
#   clusterIP: None
#   selector:
#     app: mysql
